config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"

  # Restful design routes
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

  # API endpoints
  namespace :api do
    resources :users do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :show, :new, :create]
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true

  after_save :update_posts_counter

  def update_posts_counter
    post.increment!(:comments_counter)
  end

  after_destroy :decrement_posts_comments_counter
  def decrement_posts_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  before_action :current_post, only: [:index]
  before_action :find_author, only: [:index]
  skip_before_action :authenticate_user!, only: %i[index show create new]
  skip_before_action :verify_authenticity_token
  def index
    comments = @post.comments.where(author_id: @user.id)
    render json: comments
  end

  def show; end

  def create
    @comment = Comment.new(post_id: params[:post_id], author_id: params[:user_id], **comment_params)
    if @comment.save
      render json: @comment
    else
      render json: @comment.errors.full_messages, status: :unprocessable_entity
    end
  end
  # Get current post

  private

  def find_author
    @user = User.find(params[:user_id])
  end

  def current_post
    @post = Post.find(params[:post_id])
  end

  # Parameters
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = Comment.new(post_id: params[:post_id], author_id: current_user.id, **comment_params)

    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      flash.now[:error] = 'Error: Couldnot create comment'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if comment.destroy
      redirect_to user_post_path, notice: 'Comment was successfully deleted.'
    else
      flash.now[:error] = 'Error: Couldnot delete comment'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<div class="w-full">
  <h3 class="text-center text-blue-600 mb-4">Comment on Post</h3>

  <%= form_with model: @comment, url: user_post_comments_path do |form| %>
    <div>
      <%= 
        form.text_area :text, 
        placeholder: 'Write comment',
        class: "border-none rounded-md w-full mb-4",
        rows: 5,
        required: true 
      %>

      <ul>
      <% @post.errors.full_messages_for(:text).each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>

    <div class="text-center">
      <%=
        form.submit "Submit",
        class: "btn-primary"  
      %>
    </div>

    <div class="w-full">
      <%= 
        link_to 'Go Back', user_path(current_user.id),
        class: "bg-gray-400 px-5 py-2 rounded hover:text-gray-50 hover:bg-gray-600" 
      %>
    </div>

  <% end %>
</div>