config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"

  # Restful design routes
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

  # API endpoints
  namespace :api do
    resources :users do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :show, :new, :create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true, length: { in: 2..25 }
  validates :bio, length: { minimum: 5, too_short: 'Bio should be more than 20 characters' }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.first(3)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @users = User.all
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order('created_at DESC')
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
<div class="
  flex flex-row justify-center gap-3 w-3/4 mx-auto mb-[10px] h-auto
  bg-blue-200 p-2 rounded-lg hover:bg-gray-100 sm:flex sm:flex-col sm:gap-2
  md:flex md:flex-row md:gap-3
  ">
  <div class="rounded-md">
    <%= 
      image_tag(user.photo,
      :alt => "User profile photo.",
      :class => "display-photo rounded-2xl")
    %>
  </div>

  <div class="w-1/2 flex flex-col items-start justify-center">
    <h1 class="username uppercase text-xl text-blue-600 xs:text-[15px] md:text-[15px] lg:text-[20px]">
      <%= user.name %>
    </h1>
    <p class="text-gray-600">
      No of posts: <%= user.posts_counter %>
    </p>
  </div>
</div>

app/views/users/_user_post_card.html.erb
<div class="border-none p-4 mb-4 bg-blue-200 rounded-md">
  <h3 class="mb-2 text-blue-900">Post #<%= post.id %></h3>
  <div>
    <h4 class="uppercase text-blue-600 font-semibold"><%= post.title %></h4>
    <p class="text-gray-800 mb-3"><%= post.text %></p>
    <div>
      <span class="text-gray-500 pr-3 italic">Comments: <%= post.comments_counter %></span>
      <span class="text-gray-500 italic">Likes: <%= post.likes_counter %></span>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="home-page">
  <h1 class="header uppercase text-4xl mb-2">Welcome </h1>
  <p class="text-center mb-4">List of all available users.</p>
  <div class="grid lg:grid-cols-3 w-full md:grid-cols-2 sm:grid-cols-1">
    <% @users.each do |user| %>
      <%= link_to user_path(user.id) do %>
        <%= render partial: 'user_info', locals: { user: user } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-show-post">
  <%= render partial: "user_info", locals: {user: @user} %>
  <div class="w-3/4 mx-auto border-none">
    <div class="pt-4 pb-4">
      <h3 class="uppercase text-[1.5em]">Bio</h3>
      <p class="italic text-gray-600">
        <%= @user.bio %>
      </p>
    </div>

    <div class="">
      <% if @user.posts.empty? %>
      <div class="text-center p-4 bg-gray-100 mb-5 rounded-md">
        <p class="text-gray-400">No posts for user!</p>
        </div>
      <% else %>
        <% @user.most_recent_posts.each do |post| %>
          <%= link_to user_post_path(@user.id, post.id) do %>
            <%= render partial: "user_post_card", locals: {post: post} %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <div>
  
  <div class="w-2/4 text-center bg-blue-200 mb-4 hover:text-gray-50 hover:bg-blue-600">
    <% if @user.posts_counter > 5 %>
      <%= link_to user_posts_path(@user.id) do %>
        <p class="see-all-posts">See all posts</p>
      <% end %>
    <% end %>
  </div>

  <% if current_user.id == @user.id %>
    <div class="flex flex-row items-center gap-5 mb-5">
      <%= 
        link_to 'Create Post',
        new_user_post_url(@user),
        class: "
          text-blue-600 px-4 py-2 bg-blue-200 border-none rounded-md
          hover:text-gray-50 hover:bg-blue-600
        "
      %>
    </div>
  <% end %>

  <div>
    <%= link_to 'Back', users_url, class: "bg-gray-400 px-5 py-2 rounded hover:text-gray-50 hover:bg-gray-600" %>
  </div>

</div>