config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"

  # Restful design routes
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

  # API endpoints
  namespace :api do
    resources :users do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :show, :new, :create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, length: { maximum: 250 }, presence: true
  validates :text, length: { minimum: 5 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter
  after_destroy :decrement_author_posts_counter

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def most_recent_comments
    comments.includes(:author).order(id: :desc).limit(5)
  end

  def decrement_author_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @posts = User.find(params[:user_id]).posts
    render json: @posts
  end

  def show; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    user_id = params[:user_id]
    @user = User.includes(posts: [:comments]).find(user_id)
  end

  def show
    author_id = params[:user_id]
    post_id = params[:id]
    @user = User.find(author_id)
    @post = @user.posts.includes(:comments, :likes).find(post_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(author_id: current_user.id, **post_params, comments_counter: 0, likes_counter: 0)

    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to "/users/#{@post.author_id}/posts/"
    else
      flash.now[:error] = 'Oops. Something went wrong'
      render :new, status: :unprocessable_entity
    end
  end

  # Destroy posts
  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = 'Post was successfully deleted'
      redirect_to user_posts_path
    else
      puts "Couldn't delete post"
      flash.now[:error] = 'Oops. Could not delete the post'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="user-specific-post">
  <% if notice %>
  <p class="border-green-50 text-white bg-green-400 rounded-md px-6 py-2 mb-4 text-center">
    <%= notice %>
  </p>
  <% end %>

  <%= render partial: "users/user_info", locals: {user: @user} %>

  <div class="post-info">
    <% @user.posts.each do |post| %>
      <%= link_to user_post_path(@user.id, post.id) do %>
        <%= render partial: "users/user_post_card", locals: {post: post} %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="flex flex-col flex-start w-3/4">
  <div class="mb-4">
    <%= 
      link_to 'Create new post',
      new_user_post_url(@user),
      class: "text-blue-600 px-4 py-2 bg-blue-200 border-none rounded-md
        hover:text-gray-50 hover:bg-blue-600"
    %>
  </div>
  <div>
    <%= 
      link_to 'Go Back', user_path(@user.id),
      class: "bg-gray-400 px-5 py-2 rounded hover:text-gray-50 hover:bg-gray-600"
    %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="flex flex-col gap-3 mx-auto w-full">
  <h2 class="uppercase text-blue-600 text-center">Create a new post</h2>

  <div class="w-2/3 mx-auto">
    <% @post.errors.full_messages_for(:title).each do |msg| %>
      <li class="bg-red-400 px-4 py-2 text-white list-none rounded-md">
        <%= msg %>
      </li>
    <% end %>
  </div>
  <div class="w-1/2 mx-auto">
    <% @post.errors.full_messages_for(:text).each do |msg| %>
      <li class="bg-red-400 px-4 py-2 text-white list-none rounded-md">
        <%= msg %>
      </li>
    <% end %>
  </div>

  <%= form_with model: @post, url: user_posts_path do |form| %>
    <div class="flex flex-col gap-2 mb-3">
      <%= form.label :title%>
      <%= 
        form.text_field :title,
        placeholder: "Enter title...",
        required: true,
        class: "border-none rounded-md placeholder-gray-500 w-full"
      %>
    </div>

    <div class="flex flex-col gap-2 mb-3">
      <%= form.label :text, "Write post:" %>
      <%=
        form.text_area :text,
        class: "border-none rounded-md w-full",
        placeholder: "Write post...",
        required: true
      %>
    </div>

    <div>
      <%= form.submit  "Create Post", class: "btn-primary" %>
    </div>

    <div class="w-full">
      <%= 
        link_to 'Go Back', user_path(current_user.id),
        class: "bg-gray-400 px-5 py-2 rounded hover:text-gray-50 hover:bg-gray-600" 
      %>
    </div>
  <% end %>


</div>

app/views/posts/show.html.erb
<div class="border-none flex flex-col gap-4 w-3/4">
  <% if notice %>
    <p class="border-green-50 text-white bg-green-400 rounded-md px-6 py-2 mb-4 text-center">
      <%= notice %>
    </p>
  <% end %>
  <div class="w-full mb-4 bg-blue-200 px-4 py-2 rounded-md">
    <div class="flex flex-col gap-3">
      <h3 class="text-blue-800 uppercase text-2xl">
        <%= @post.title %>
      </h3>
      <p>
        <%= @post.text %>
      </p>
      <p class="italic text-gray-500 text-sm">
        <span>Comments: <%= @post.comments_counter %><span>
        <span>Likes: <%= @post.likes_counter %></span>
      </p>

      <p><span class="capitalize text-blue-800 italic">Author: </span><%= @user.name %></p>
      </div>
  </div>

  <div class="w-full">
    <% if @post.comments.empty? %>
      <p class="bg-gray-300 px-4 py-2 rounded-md text-gray-800">No comments.</p>
    <% else %>
      <% @post.comments.each do |comment| %>
        <div class="flex gap-5">
          <p><%= comment.author.name %>: <%= comment.text %></p>
            <% if can? :destroy, @post %>
              <%=
                button_to 'DEL',
                user_post_comment_path(@user, @post, comment),
                method: :delete, data: { confirm: "Are you sure?"},
                class: "bg-red-200 text-sm px-2 rounded-md text-red-600 
                  hover:bg-red-600 hover:text-gray-50"       
              %>
            <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="">
    <div class="">
      <%=
        link_to 'New comment',
        new_user_post_comment_path(@user, @post),
        class: "text-blue-600 px-4 py-2 bg-blue-200 border-none rounded-md
          hover:text-gray-50 hover:bg-blue-600"
      %>
    </div> <br/>
    
    <div class="flex flex-row gap-4">
      <%= form_with url: user_post_likes_path(@post.author, @post), method: :post do |form| %>
        <%= 
          form.submit "Like",
          class:"bg-green-400 px-4 py-1 rounded-md text-gray-50 cursor-pointer hover:text-gray-600"
        %>
      <% end %>
      <div>
        <% if can? :destroy, @post %>
          <%=
            button_to "Delete Post",
            user_post_path(@user.id),
            method: :delete, data: { confirm: "Delete?" },
            class: "text-red-600 px-4 py-1 bg-red-200 border-none rounded-md
              hover:text-gray-50 hover:bg-red-600"  
          %>
        <% end %>
      </div>
    </div>

  </div>

  <p>
    <%=
      link_to 'Back',
      user_path(@user.id),
      class: "bg-gray-400 px-5 py-2 rounded hover:text-gray-50 hover:bg-gray-600"
    %>
  </p>

</div>